ensemble_methods:
- voting
- stacking
feature_engineering: true
feature_selection: true
max_trials: 100
metric: auto
models:
  catboost: true
  lgb: true
  lr: true
  rf: true
  svm: false
  xgb: true
preprocessing:
  encode_categorical: true
  handle_missing: true
  remove_outliers: false
  scale_features: true
problem_type: auto
random_state: 42
target_column: target
test_size: 0.2
cv_folds: 5