services:
  inference:
    container_name: inference
    env_file:
      - .env
    build: .
    command: python -u /app/app.py
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://inference:8000/inference/${TOKEN}"]
      interval: 10s
      timeout: 5s
      retries: 12
    volumes:
      - ./inference-data:/app/data
      - ./.env:/app/.env:ro
  
  updater:
    container_name: updater
    build: .
    environment:
      - INFERENCE_API_ADDRESS=http://inference:8000
    command: >
      sh -c "
      while true; do
        python -u /app/update_app.py;
        sleep 24h;
      done
      "
    depends_on:
      inference:
        condition: service_healthy

  worker:
    container_name: worker
    image: alloranetwork/allora-offchain-node:v0.6.0
    platform: linux/amd64
    pull_policy: always
    volumes:
      - ./worker-data:/data
    depends_on:
      inference:
        condition: service_healthy
    env_file:
      - ./worker-data/env_file
    environment:
      - INFERENCE_API_ADDRESS=http://inference:8000

volumes:
  inference-data:
  worker-data: