name: Auto Train and Optimize

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  train:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Create .env
        run: |
          echo "APP_BASE_PATH=${{ github.workspace }}" >> .env
          echo "TOKEN=SOL" >> .env
          echo "TRAINING_DAYS=400" >> .env
          echo "TIMEFRAME=1D" >> .env
          echo "MODEL=AUTO" >> .env
          echo "REGION=US" >> .env
          echo "DATA_PROVIDER=coingecko" >> .env
          echo "CG_API_KEY=${{ secrets.CG_API_KEY }}" >> .env

      - name: Run training + optimization
        env:
          REPO_NAME: ${{ github.repository }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python app.py & sleep 10
          curl -sS http://127.0.0.1:8000/update || true
          curl -sS http://127.0.0.1:8000/metrics || true

      - name: Commit and push artifacts
        run: |
          git config user.name "gh-actions"
          git config user.email "actions@github.com"
          git add data/ || true
          git add . || true
          git commit -m "ci: auto-train and optimize" || echo "No changes"
          git push
